Attempt at bugfix: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.                    2017-01-11 13:59:43.356 ERROR 8828 --- [           main] o.s.boot.SpringApplication               : Application startup faile                    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133)                    d                            at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:474)
                           at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
                   org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
                           at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
                           at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:133)
                           at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
                           at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:474)
                           at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
                           at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
                           at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
                           at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
                           at todomvc.Main.main(Main.java:8)
                           at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
                   Caused by: org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
                           at org.springframework.boot.SpringApplication.run(SpringApplication.java:957)
                           at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:183)
                           at org.springframework.boot.SpringApplication.run(SpringApplication.java:946)
                           at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:156)
                           at todomvc.Main.main(Main.java:8)
                           at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130)
                   Caused by: org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
                           ... 7 more
                           at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:183)
                           at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:156)
                           at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:130)
                           ... 7 common frames omitted