Attempt at bugfix: "C:\Program Files\Java\jdk1.8.0_102\bin\java" -ea -Didea.launcher.port=7533 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3.1\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3.1\lib\idea_rt.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.3.1\plugins\junit\lib\junit-rt.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\rt.jar;E:\graphiql-java\graphql-server\build\classes\test;E:\graphiql-java\graphql-server\build\resources\test;E:\graphiql-java\graphql-server\build\classes\main;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\com.graphql-java\graphql-java\2015-08-16T21-37-10\11d9dea8df0a3f643065eb68e8c21a8e1c22f2a0\graphql-java-2015-08-16T21-37-10.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-starter-web\1.4.3.RELEASE\a0dcc919eda8e8ecb6f13f52a30e6afbb8266103\spring-boot-starter-web-1.4.3.RELEASE.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-starter-security\1.4.3.RELEASE\7be355e82dee368afbd909b48a5db3b81e981d\spring-boot-starter-security-1.4.3.RELEASE.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\commons-io\commons-io\2.5\2852e6e05fbb95076fc091f6d1780f1f8fe35e0f\commons-io-2.5.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\com.google.guava\guava\20.0\89507701249388e1ed5ddcf8c41f4ce1be7831ef\guava-20.0.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.eclipse.aether\aether-api\1.0.0.v20140518\be68e917f454dcd841865ad7cf9b7615b26a51f7\aether-api-1.0.0.v20140518.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.eclipse.aether\aether-util\1.0.0.v20140518\7df5ba98ce8b78985d75fdd8c2981fe69234ef85\aether-util-1.0.0.v20140518.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.eclipse.aether\aether-impl\1.0.0.v20140518\a5ee67be2c99dfb95ad61235d749c92ae09c926e\aether-impl-1.0.0.v20140518.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.eclipse.aether\aether-connector-basic\1.0.0.v20140518\fd563f66fc1b6b908934639f87b4e0a0f43809c3\aether-connector-basic-1.0.0.v20140518.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.eclipse.aether\aether-transport-file\1.0.0.v20140518\fd2844e8b329b929a823a351fe5adb16e49a2dfb\aether-transport-file-1.0.0.v20140518.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.eclipse.aether\aether-transport-http\1.0.0.v20140518\a5a17a9d97a3694182b0b3539d047014c8e01ad6\aether-transport-http-1.0.0.v20140518.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.eclipse.aether\aether-transport-wagon\1.0.0.v20140518\19be874c32183409ed76fcd3ecc05b28f3e06e62\aether-transport-wagon-1.0.0.v20140518.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-aether-provider\3.1.0\dda2231a2be2768109d474805c702b76a8e794e6\maven-aether-provider-3.1.0.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.apache.maven.wagon\wagon-ssh\1.0\b7fd089a30ceacc4034a8e993f83c417057dcc7f\wagon-ssh-1.0.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.easytesting\fest-assert-core\2.0M10\cb7c91cf614901928ae405f19d9bcdedf82781db\fest-assert-core-2.0M10.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\junit\junit\4.11\4e031bb61df09069aeb2bffb4019e7a5034a4ee0\junit-4.11.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.antlr\antlr4-runtime\4.5.1\7d7288bbe0599b32b844971f270ed001a661357\antlr4-runtime-4.5.1.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-starter\1.4.3.RELEASE\c99bad104719e947b3f9aa2b7569583805e4c5d5\spring-boot-starter-1.4.3.RELEASE.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-starter-tomcat\1.4.3.RELEASE\61c48035a7a3b06b42fdd07b7109e562077b3792\spring-boot-starter-tomcat-1.4.3.RELEASE.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.hibernate\hibernate-validator\5.2.4.Final\fb18766b576aa6632bcfe9a20a023cbd52bf9769\hibernate-validator-5.2.4.Final.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-databind\2.8.5\b3035f37e674c04dafe36a660c3815cc59f764e2\jackson-databind-2.8.5.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.springframework\spring-web\4.3.5.RELEASE\6641daccf2fddafc8358144f3a4f999130fdf144\spring-web-4.3.5.RELEASE.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.springframework\spring-webmvc\4.3.5.RELEASE\c624659217edab07d8279fb0f90462136f089220\spring-webmvc-4.3.5.RELEASE.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.springframework\spring-aop\4.3.5.RELEASE\4f113218af716bd8d174c411f19b26418b5a70f6\spring-aop-4.3.5.RELEASE.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.springframework.security\spring-security-config\4.1.4.RELEASE\cdbe774537be58d3d7ca0662619bf9f57b5c8209\spring-security-config-4.1.4.RELEASE.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.springframework.security\spring-security-web\4.1.4.RELEASE\f3560a3e82a910b8005f28552e4cb0660ce50b26\spring-security-web-4.1.4.RELEASE.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.eclipse.aether\aether-spi\1.0.0.v20140518\985a9a12b904fb3bafd4dc6b49f6a084845703a1\aether-spi-1.0.0.v20140518.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpclient\4.2.6\e4ca30a6a3a075053a61c6fc850d2432dc012ba7\httpclient-4.2.6.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.apache.maven.wagon\wagon-provider-api\1.0\12bcd211158c0c09b027d06b70371861398fedea\wagon-provider-api-1.0.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-model\3.1.0\82b2f097c1cc9a8d0e6b99af5e56327d5002c30f\maven-model-3.1.0.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-model-builder\3.1.0\13ba294cedb659c3851f0c2980af7f44bcc6a8e0\maven-model-builder-3.1.0.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-repository-metadata\3.1.0\77bb2c383b1654b158cf9f905f4105d9d522fc7e\maven-repository-metadata-3.1.0.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.eclipse.sisu\org.eclipse.sisu.plexus\0.0.0.M2a\7510dc8dfe27a0b57c17601bc760b7b0c8f95fa\org.eclipse.sisu.plexus-0.0.0.M2a.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.codehaus.plexus\plexus-component-annotations\1.5.5\c72f2660d0cbed24246ddb55d7fdc4f7374d2078\plexus-component-annotations-1.5.5.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.codehaus.plexus\plexus-utils\3.0.10\65e6460a49460d2ca038f8644ff9ae6d878733b8\plexus-utils-3.0.10.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\com.jcraft\jsch\0.1.44-1\2e9ae08de5a71bd0e0d3ba2558598181bfa71d4e\jsch-0.1.44-1.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.apache.maven.wagon\wagon-ssh-common\1.0\22ee386761863f4edf723f584ba0666985289c51\wagon-ssh-common-1.0.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.easytesting\fest-util\1.2.5\c4a8d7305b23b8d043be12c979813b096df11f44\fest-util-1.2.5.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.hamcrest\hamcrest-core\1.3\42a25dc3219429f0e5d060061f71acb49bf010a0\hamcrest-core-1.3.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.springframework.boot\spring-boot\1.4.3.RELEASE\17f94def4460075afdfba6bf8f897cd1fc95bf77\spring-boot-1.4.3.RELEASE.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-autoconfigure\1.4.3.RELEASE\41df1bfbdd4ae4e8499ebe1a4bc613bda316d6e1\spring-boot-autoconfigure-1.4.3.RELEASE.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-starter-logging\1.4.3.RELEASE\1c58783c0694abf695babfd39829922d2d501ec2\spring-boot-starter-logging-1.4.3.RELEASE.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.springframework\spring-core\4.3.5.RELEASE\80299e3f80e8c6d5c076db2ba6adf44a4b52f578\spring-core-4.3.5.RELEASE.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.yaml\snakeyaml\1.17\7a27ea250c5130b2922b86dea63cbb1cc10a660c\snakeyaml-1.17.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.apache.tomcat.embed\tomcat-embed-core\8.5.6\960834b5abc6b2135250487abf6c060a0fa5a22e\tomcat-embed-core-8.5.6.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.apache.tomcat.embed\tomcat-embed-el\8.5.6\a102298d8dc72f4065533d5962953d753b172602\tomcat-embed-el-8.5.6.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.apache.tomcat.embed\tomcat-embed-websocket\8.5.6\6f6940a216b380ea8506530c374fcfeef820ba54\tomcat-embed-websocket-8.5.6.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\javax.validation\validation-api\1.1.0.Final\8613ae82954779d518631e05daa73a6a954817d5\validation-api-1.1.0.Final.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.jboss.logging\jboss-logging\3.2.1.Final\fedf11b3d4665a434b554a5891fe7f208f029f45\jboss-logging-3.2.1.Final.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\com.fasterxml\classmate\1.1.0\dbbd699a1486ad0f2ed6f5af6cfed66acacb9056\classmate-1.1.0.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-annotations\2.8.0\45b426f7796b741035581a176744d91090e2e6fb\jackson-annotations-2.8.0.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-core\2.8.5\60d059f5d2930ccd1ef03535b713fd9f933d1ba7\jackson-core-2.8.5.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.springframework\spring-beans\4.3.5.RELEASE\e12bbc3277da28e2e2608a187f83091dc6c300bf\spring-beans-4.3.5.RELEASE.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.springframework\spring-context\4.3.5.RELEASE\ca3391c0e17d0138335ba51b51371661d20d56a8\spring-context-4.3.5.RELEASE.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.springframework\spring-expression\4.3.5.RELEASE\3689dc6c5b942ecde4122eac889ed87977d6f287\spring-expression-4.3.5.RELEASE.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.springframework.security\spring-security-core\4.1.4.RELEASE\382ca3b438f686c664c539a72cc6a2c81f8592fa\spring-security-core-4.1.4.RELEASE.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpcore\4.2.5\472f0f5f8dba5d1962cb9d7739feed739a31c30d\httpcore-4.2.5.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\commons-codec\commons-codec\1.6\b7f0fc8f61ecadeb3695f0b9464755eee44374d4\commons-codec-1.6.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.codehaus.plexus\plexus-interpolation\1.16\a868d4a603bd42c9dee67890c4e60e360a11838c\plexus-interpolation-1.16.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\javax.enterprise\cdi-api\1.0\44c453f60909dfc223552ace63e05c694215156b\cdi-api-1.0.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.sonatype.sisu\sisu-guice\3.1.0\97c87d15d749c86b2be1b9809b28321a1d926c7f\sisu-guice-3.1.0-no_aop.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.eclipse.sisu\org.eclipse.sisu.inject\0.0.0.M2a\17941e32c751179a9628b25f54ce5641edafb9be\org.eclipse.sisu.inject-0.0.0.M2a.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.codehaus.plexus\plexus-classworlds\2.4\ef38ff5c25f83a4a02fcd9843d85f3e47012873e\plexus-classworlds-2.4.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.codehaus.plexus\plexus-interactivity-api\1.0-alpha-6\c06f0eb818633033f09a87d14c4cfb6f39af9a37\plexus-interactivity-api-1.0-alpha-6.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\ch.qos.logback\logback-classic\1.1.8\e54f49a227611976642f81cf2106b81c1ece8bf5\logback-classic-1.1.8.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.slf4j\jul-to-slf4j\1.7.22\b0429e950b3d2bc2c39c1bacafac753edbe3781c\jul-to-slf4j-1.7.22.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.slf4j\log4j-over-slf4j\1.7.22\a527c37e9ca6c3d19ba298edd4aa344ca751a203\log4j-over-slf4j-1.7.22.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\commons-logging\commons-logging\1.2\4bfc12adfe4842bf07b657f0369c4cb522955686\commons-logging-1.2.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\javax.annotation\jsr250-api\1.0\5025422767732a1ab45d93abfea846513d742dcf\jsr250-api-1.0.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\javax.inject\javax.inject\1\6975da39a7040257bd51d21a231b76c915872d38\javax.inject-1.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\aopalliance\aopalliance\1.0\235ba8b489512805ac13a8f9ea77a1ca5ebe3e8\aopalliance-1.0.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\asm\asm\3.3.1\1d5f20b4ea675e6fab6ab79f1cd60ec268ddc015\asm-3.3.1.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\ch.qos.logback\logback-core\1.1.8\b4d1c3dea91727faf8b3d19cf4b9b972d6c0b89\logback-core-1.1.8.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.slf4j\slf4j-api\1.7.22\a1c83373863cec7ae8d89dc1c5722d8cb6ec0309\slf4j-api-1.7.22.jar;C:\Users\pisarenko\.gradle\caches\modules-2\files-2.1\org.slf4j\jcl-over-slf4j\1.7.22\86ceac14535af5a42c8fb0d06d79b925dd3cb263\jcl-over-slf4j-1.7.22.jar" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 maven.MavenSchemaTests,test
                   java.io.FileNotFoundException: File 'src\test\resources\query1.txt' does not exist

                   	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:292)
                   	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1765)
                   	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1784)
                   	at maven.MavenSchemaTests.test(MavenSchemaTests.java:22)
                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                   	at java.lang.reflect.Method.invoke(Method.java:498)
                   	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
                   	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                   	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
                   	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                   	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
                   	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
                   	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
                   	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
                   	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
                   	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
                   	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
                   	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
                   	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
                   	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
                   	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
                   	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
                   	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
                   	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                   	at java.lang.reflect.Method.invoke(Method.java:498)
                   	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

                   Process finished with exit code -1